
USE CSDLPT;
GO

IF OBJECT_ID('V_KHO', 'V') IS NOT NULL DROP VIEW V_KHO;
IF OBJECT_ID('V_KHACHHANG', 'V') IS NOT NULL DROP VIEW V_KHACHHANG;
IF OBJECT_ID('V_TONKHO', 'V') IS NOT NULL DROP VIEW V_TONKHO;
IF OBJECT_ID('V_DONHANG', 'V') IS NOT NULL DROP VIEW V_DONHANG;
IF OBJECT_ID('V_CHITIETDONHANG', 'V') IS NOT NULL DROP VIEW V_CHITIETDONHANG;
GO

CREATE VIEW V_KHO AS
    SELECT MaKho, TenKho, KhuVuc, DiaChi FROM KHO
    UNION ALL
    SELECT MaKho COLLATE DATABASE_DEFAULT, TenKho COLLATE DATABASE_DEFAULT,
           KhuVuc COLLATE DATABASE_DEFAULT, DiaChi COLLATE DATABASE_DEFAULT
    FROM [S1_MB].[CSDLPT].[dbo].[KHO]
    UNION ALL
    SELECT MaKho COLLATE DATABASE_DEFAULT, TenKho COLLATE DATABASE_DEFAULT,
           KhuVuc COLLATE DATABASE_DEFAULT, DiaChi COLLATE DATABASE_DEFAULT
    FROM [S3_MN].[CSDLPT].[dbo].[KHO];
GO

CREATE VIEW V_KHACHHANG AS
    SELECT MaKH, TenKH, KhuVuc, DiaChi, SoDienThoai FROM KHACHHANG
    UNION ALL
    SELECT MaKH COLLATE DATABASE_DEFAULT, TenKH COLLATE DATABASE_DEFAULT,
           KhuVuc COLLATE DATABASE_DEFAULT, DiaChi COLLATE DATABASE_DEFAULT,
           SoDienThoai COLLATE DATABASE_DEFAULT
    FROM [S1_MB].[CSDLPT].[dbo].[KHACHHANG]
    UNION ALL
    SELECT MaKH COLLATE DATABASE_DEFAULT, TenKH COLLATE DATABASE_DEFAULT,
           KhuVuc COLLATE DATABASE_DEFAULT, DiaChi COLLATE DATABASE_DEFAULT,
           SoDienThoai COLLATE DATABASE_DEFAULT
    FROM [S3_MN].[CSDLPT].[dbo].[KHACHHANG];
GO

CREATE VIEW V_TONKHO AS
    SELECT MaKho, MaSP, SoLuongTon FROM TONKHO
    UNION ALL
    SELECT MaKho COLLATE DATABASE_DEFAULT, MaSP COLLATE DATABASE_DEFAULT, SoLuongTon
    FROM [S1_MB].[CSDLPT].[dbo].[TONKHO]
    UNION ALL
    SELECT MaKho COLLATE DATABASE_DEFAULT, MaSP COLLATE DATABASE_DEFAULT, SoLuongTon
    FROM [S3_MN].[CSDLPT].[dbo].[TONKHO];
GO

CREATE VIEW V_DONHANG AS
    SELECT MaDH, MaKH, NgayLap, TrangThai FROM DONHANG
    UNION ALL
    SELECT MaDH COLLATE DATABASE_DEFAULT, MaKH COLLATE DATABASE_DEFAULT,
           NgayLap, TrangThai COLLATE DATABASE_DEFAULT
    FROM [S1_MB].[CSDLPT].[dbo].[DONHANG]
    UNION ALL
    SELECT MaDH COLLATE DATABASE_DEFAULT, MaKH COLLATE DATABASE_DEFAULT,
           NgayLap, TrangThai COLLATE DATABASE_DEFAULT
    FROM [S3_MN].[CSDLPT].[dbo].[DONHANG];
GO

CREATE VIEW V_CHITIETDONHANG AS
    SELECT MaDH, MaSP, MaKhoXuat, SoLuong, DonGia FROM CHITIETDONHANG
    UNION ALL
    SELECT MaDH COLLATE DATABASE_DEFAULT, MaSP COLLATE DATABASE_DEFAULT,
           MaKhoXuat COLLATE DATABASE_DEFAULT, SoLuong, DonGia
    FROM [S1_MB].[CSDLPT].[dbo].[CHITIETDONHANG]
    UNION ALL
    SELECT MaDH COLLATE DATABASE_DEFAULT, MaSP COLLATE DATABASE_DEFAULT,
           MaKhoXuat COLLATE DATABASE_DEFAULT, SoLuong, DonGia
    FROM [S3_MN].[CSDLPT].[dbo].[CHITIETDONHANG];
GO

PRINT N'=== VIEWS MÁY 2 OK ===';
SELECT 'V_KHO' AS [View], COUNT(*) AS Cnt FROM V_KHO
UNION ALL SELECT 'V_TONKHO', COUNT(*) FROM V_TONKHO;
GO
