
USE CSDLPT;
GO

PRINT N'=== RESET DỮ LIỆU DEMO ===';
PRINT N'';

UPDATE TONKHO SET SoLuongTon = 50  WHERE MaSP = 'SP001' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 80  WHERE MaSP = 'SP002' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 120 WHERE MaSP = 'SP003' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 25  WHERE MaSP = 'SP004' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 90  WHERE MaSP = 'SP005' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 60  WHERE MaSP = 'SP006' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 200 WHERE MaSP = 'SP011' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 300 WHERE MaSP = 'SP016' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 500 WHERE MaSP = 'SP021' AND MaKho = 'K001';
UPDATE TONKHO SET SoLuongTon = 40  WHERE MaSP = 'SP026' AND MaKho = 'K001';

UPDATE TONKHO SET SoLuongTon = 30  WHERE MaSP = 'SP001' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 45  WHERE MaSP = 'SP002' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 35  WHERE MaSP = 'SP007' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 55  WHERE MaSP = 'SP008' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 100 WHERE MaSP = 'SP012' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 180 WHERE MaSP = 'SP017' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 400 WHERE MaSP = 'SP022' AND MaKho = 'K002';
UPDATE TONKHO SET SoLuongTon = 25  WHERE MaSP = 'SP027' AND MaKho = 'K002';

UPDATE TONKHO SET SoLuongTon = 70  WHERE MaSP = 'SP003' AND MaKho = 'K003';
UPDATE TONKHO SET SoLuongTon = 80  WHERE MaSP = 'SP009' AND MaKho = 'K003';
UPDATE TONKHO SET SoLuongTon = 60  WHERE MaSP = 'SP013' AND MaKho = 'K003';
UPDATE TONKHO SET SoLuongTon = 250 WHERE MaSP = 'SP018' AND MaKho = 'K003';
UPDATE TONKHO SET SoLuongTon = 350 WHERE MaSP = 'SP023' AND MaKho = 'K003';
UPDATE TONKHO SET SoLuongTon = 45  WHERE MaSP = 'SP028' AND MaKho = 'K003';

UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 35  WHERE MaSP = 'SP001' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 55  WHERE MaSP = 'SP002' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 90  WHERE MaSP = 'SP003' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 70  WHERE MaSP = 'SP006' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 110 WHERE MaSP = 'SP010' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 45  WHERE MaSP = 'SP014' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 220 WHERE MaSP = 'SP016' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 160 WHERE MaSP = 'SP019' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 30  WHERE MaSP = 'SP024' AND MaKho = 'K004';
UPDATE [S2_MT].[CSDLPT].[dbo].[TONKHO] SET SoLuongTon = 85  WHERE MaSP = 'SP029' AND MaKho = 'K004';

DELETE FROM CHITIETDONHANG WHERE MaDH LIKE 'DH26%';
DELETE FROM DONHANG WHERE MaDH LIKE 'DH26%';

PRINT N'';
PRINT N'✅ RESET HOÀN TẤT!';
PRINT N'';

SELECT 'S1-K001' AS Kho, MaSP, SoLuongTon FROM TONKHO
WHERE MaKho = 'K001' AND MaSP IN ('SP001','SP002','SP003')
UNION ALL
SELECT 'S2-K004', MaSP COLLATE DATABASE_DEFAULT, SoLuongTon
FROM [S2_MT].[CSDLPT].[dbo].[TONKHO]
WHERE MaKho = 'K004' AND MaSP IN ('SP001','SP002','SP003');
GO
