
USE CSDLPT;
GO

PRINT N'=== TRUY VẤN 1: Cục bộ tại S1 ===';
SELECT P.TenSP, P.GiaBan, T.SoLuongTon
FROM SP_PUBLIC P
    INNER JOIN TONKHO T ON P.MaSP = T.MaSP
    INNER JOIN KHO K ON T.MaKho = K.MaKho
WHERE K.MaKho = 'K001'
  AND P.MaDM = 'DM01';
GO

PRINT N'=== TRUY VẤN 2: Tổng hợp cục bộ ===';

SELECT MaSP, SUM(SoLuongTon) AS TongTonKho
FROM V_TONKHO
WHERE MaSP = 'SP001'
GROUP BY MaSP;
GO

SELECT 'S1' AS Tram, SUM(SoLuongTon) AS TonCucBo
FROM TONKHO WHERE MaSP = 'SP001'
UNION ALL
SELECT 'S2', SUM(SoLuongTon)
FROM [S2_MT].[CSDLPT].[dbo].[TONKHO] WHERE MaSP = 'SP001'
UNION ALL
SELECT 'S3', SUM(SoLuongTon)
FROM [S3_MN].[CSDLPT].[dbo].[TONKHO] WHERE MaSP = 'SP001';
GO

PRINT N'=== TRUY VẤN 3: Phép nối nửa ===';

SELECT D.MaDH,
       D.MaKH COLLATE DATABASE_DEFAULT AS MaKH,
       CT.MaSP COLLATE DATABASE_DEFAULT AS MaSP,
       CT.MaKhoXuat COLLATE DATABASE_DEFAULT AS MaKhoXuat,
       CT.SoLuong
FROM [S3_MN].[CSDLPT].[dbo].[DONHANG] D
    INNER JOIN [S3_MN].[CSDLPT].[dbo].[CHITIETDONHANG] CT
        ON D.MaDH COLLATE DATABASE_DEFAULT = CT.MaDH COLLATE DATABASE_DEFAULT
WHERE CT.MaKhoXuat COLLATE DATABASE_DEFAULT IN (
    SELECT MaKho FROM KHO
);
GO

PRINT N'=== TRUY VẤN 4: GROUP BY cục bộ 2 giai đoạn ===';

SELECT KhuVuc, SUM(DoanhThu) AS TongDoanhThu FROM (

    SELECT 'MB' AS KhuVuc, SUM(CT.SoLuong * CT.DonGia) AS DoanhThu
    FROM CHITIETDONHANG CT
    UNION ALL

    SELECT 'MT', SUM(CT.SoLuong * CT.DonGia)
    FROM [S2_MT].[CSDLPT].[dbo].[CHITIETDONHANG] CT
    UNION ALL

    SELECT 'MN', SUM(CT.SoLuong * CT.DonGia)
    FROM [S3_MN].[CSDLPT].[dbo].[CHITIETDONHANG] CT
) AS T

GROUP BY KhuVuc
ORDER BY TongDoanhThu DESC;
GO

PRINT N'=== TRUY VẤN 5: Top 10 sản phẩm bán chạy ===';

SELECT TOP 10
    P.MaSP, P.TenSP, SUM(TongBan) AS TongSoLuongBan
FROM SP_PUBLIC P
INNER JOIN (

    SELECT MaSP COLLATE DATABASE_DEFAULT AS MaSP, SUM(SoLuong) AS TongBan
    FROM CHITIETDONHANG GROUP BY MaSP
    UNION ALL

    SELECT MaSP COLLATE DATABASE_DEFAULT, SUM(SoLuong)
    FROM [S2_MT].[CSDLPT].[dbo].[CHITIETDONHANG] GROUP BY MaSP
    UNION ALL

    SELECT MaSP COLLATE DATABASE_DEFAULT, SUM(SoLuong)
    FROM [S3_MN].[CSDLPT].[dbo].[CHITIETDONHANG] GROUP BY MaSP
) AS T ON P.MaSP = T.MaSP
GROUP BY P.MaSP, P.TenSP
ORDER BY TongSoLuongBan DESC;
GO
